### ISSUE TITLE
Copyright symbol

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/flexing-your-muscles#1]
@thomasjbradley 

Could you put a copy-pasteable copyright symbol in the sidebar for this assignment? Or add one into the README? Googling is too hard

:D :D :D :D :D :D

**Comment by thomasjbradley** [comment]
I added a `content.txt` into the repo.

**Comment by MacKenzieRose** [comment]
Awesome! Thanks, @thomasjbradley . You're the best.
